daemon off;
worker_processes 1;
pid /var/run/nginx/nginx-master.pid;
error_log /var/log/nginx/error.log;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile      on;

    client_body_temp_path /var/tmp/nginx/client_body_temp;
    proxy_temp_path       /var/tmp/nginx/proxy_temp;
    fastcgi_temp_path     /var/tmp/nginx/fastcgi_temp;
    uwsgi_temp_path       /var/tmp/nginx/uwsgi_temp;
    scgi_temp_path        /var/tmp/nginx/scgi_temp;

    server {
        listen 8080;
        server_name _;
        root /usr/local/www/site;
        index index.html;
        port_in_redirect off;

        location / {
            try_files $uri $uri/ =404;
        }

        error_page 404 /404.html;
    }
}
