base_url = "https://domdev.su"
title = "domdev"
description = "Пишу о том, что мне интересно: разработка, системное администрирование, железо."
default_language = "ru"

generate_feeds = true
feed_filenames = ["atom.xml"]

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[languages.en]
title = "domdev"
description = "Writing about things I find interesting: development, systems administration, hardware."
generate_feeds = true

[markdown]

[markdown.highlighting]
theme = "catppuccin-latte"

[extra]
# Put all your custom variables here
