base_url = "https://domdev.su"
title = "zeslava"
description = ""
default_language = "ru"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[languages.en]
title = "zeslava"
description = ""

[markdown]

[markdown.highlighting]
theme = "catppuccin-latte"

[extra]
# Put all your custom variables here
